// data.js - Shortcut Database (counts are computed at runtime, not hardcoded)
// Version 2.1 - Windows, macOS, Linux + popular app shortcuts
// Last updated: 2026

const SHORTCUTS_DB = {
    // ==================== WINDOWS OS SHORTCUTS ====================
    windows_os: {
        id: "windows_os",
        name: "Windows OS",
        platform: "windows",
        icon: "fab fa-windows",
        color: "#00e5ff",
        description: "Complete Windows operating system keyboard shortcuts for navigation, window management, and system commands",
        categories: ["General", "Windows Key", "Dialog Box", "File Explorer", "Virtual Desktops", "Taskbar", "Settings", "Command Prompt", "Window Management"],
        shortcuts: [
            { keys: "Ctrl + C", action: "Copy", category: "General", description: "Copy selected items to clipboard", useCase: "Copy text, files, or images", tips: "Works across all applications", os_specific: "Windows" },
            { keys: "Ctrl + X", action: "Cut", category: "General", description: "Cut selected items", useCase: "Move files or text", tips: "Use with Ctrl+V to paste", os_specific: "Windows" },
            { keys: "Ctrl + V", action: "Paste", category: "General", description: "Paste clipboard content", useCase: "Insert copied/cut content", tips: "Ctrl+Shift+V for plain text", os_specific: "Windows" },
            { keys: "Ctrl + Z", action: "Undo", category: "General", description: "Undo last action", useCase: "Revert mistakes", tips: "Multiple undo in most apps", os_specific: "Windows" },
            { keys: "Ctrl + Y", action: "Redo", category: "General", description: "Redo undone action", useCase: "Restore undone changes", tips: "Some apps use Ctrl+Shift+Z", os_specific: "Windows" },
            { keys: "Ctrl + A", action: "Select All", category: "General", description: "Select all items", useCase: "Quickly select everything", tips: "Works in files and text", os_specific: "Windows" },
            { keys: "Ctrl + S", action: "Save", category: "General", description: "Save current document", useCase: "Quick save work", tips: "Use frequently to avoid data loss", os_specific: "Windows" },
            { keys: "Ctrl + F", action: "Find", category: "General", description: "Search within document/page", useCase: "Find specific text", tips: "Ctrl+H for find and replace", os_specific: "Windows" },
            { keys: "Alt + Tab", action: "Switch Applications", category: "General", description: "Cycle through open apps", useCase: "Quick app switching", tips: "Hold Alt and press Tab repeatedly", os_specific: "Windows" },
            { keys: "Alt + F4", action: "Close Window", category: "General", description: "Closes current window", useCase: "Quickly close apps", tips: "On desktop opens shutdown", os_specific: "Windows" },
            { keys: "Ctrl + Alt + Del", action: "Security Screen", category: "General", description: "Opens security options", useCase: "Lock, switch user, task manager", tips: "Classic Windows shortcut", os_specific: "Windows" },
            { keys: "Windows + D", action: "Show Desktop", category: "Windows Key", description: "Minimize all windows", useCase: "Quickly access desktop", tips: "Press again to restore", os_specific: "Windows" },
            { keys: "Windows + E", action: "File Explorer", category: "Windows Key", description: "Open File Explorer", useCase: "Browse files quickly", tips: "Opens This PC by default", os_specific: "Windows" },
            { keys: "Windows + L", action: "Lock Computer", category: "Windows Key", description: "Lock your PC", useCase: "Secure when leaving desk", tips: "Requires password to unlock", os_specific: "Windows" },
            { keys: "Windows + R", action: "Run Dialog", category: "Windows Key", description: "Open Run command", useCase: "Launch programs quickly", tips: "Type 'cmd' for command prompt", os_specific: "Windows" },
            { keys: "Windows + I", action: "Open Settings", category: "Windows Key", description: "Opens Windows Settings", useCase: "Configure system", tips: "Quick access to settings", os_specific: "Windows" },
            { keys: "Windows + V", action: "Clipboard History", category: "Windows Key", description: "Opens clipboard history", useCase: "Access multiple copied items", tips: "Enable in settings first", os_specific: "Windows" },
            { keys: "Windows + Period (.)", action: "Emoji Panel", category: "Windows Key", description: "Opens emoji picker", useCase: "Insert emojis", tips: "Also has GIFs and symbols", os_specific: "Windows" },
            { keys: "Windows + Tab", action: "Task View", category: "Windows Key", description: "Opens virtual desktops", useCase: "Manage multiple desktops", tips: "Create new desktops", os_specific: "Windows" },
            { keys: "Windows + Shift + S", action: "Screenshot (Snipping Tool)", category: "Windows Key", description: "Take partial screenshot", useCase: "Capture specific area", tips: "Saves to clipboard", os_specific: "Windows" },
            { keys: "Windows + PrtScn", action: "Full Screenshot", category: "Windows Key", description: "Saves full screen screenshot", useCase: "Capture entire screen", tips: "Saves to Pictures/Screenshots", os_specific: "Windows" },
            { keys: "Ctrl + Shift + Esc", action: "Task Manager", category: "General", description: "Open Task Manager", useCase: "End unresponsive apps", tips: "Ctrl+Alt+Delete also works", os_specific: "Windows" },
            { keys: "Windows + X", action: "Quick Link Menu", category: "Windows Key", description: "Opens power user menu", useCase: "Access system tools quickly", tips: "Also called WinX menu", os_specific: "Windows" },
            { keys: "Windows + A", action: "Action Center", category: "Windows Key", description: "Opens notification center", useCase: "Check notifications", tips: "Quick settings access", os_specific: "Windows" },
            { keys: "Windows + S", action: "Search", category: "Windows Key", description: "Opens Windows search", useCase: "Find files and apps", tips: "Type to search instantly", os_specific: "Windows" },
            { keys: "F2", action: "Rename", category: "File Explorer", description: "Rename selected item", useCase: "Quickly rename files", tips: "Works in File Explorer", os_specific: "Windows" },
            { keys: "F5", action: "Refresh", category: "File Explorer", description: "Refresh current view", useCase: "Update file list", tips: "Use after adding files", os_specific: "Windows" },
            { keys: "Delete", action: "Move to Recycle Bin", category: "File Explorer", description: "Delete selected items", useCase: "Remove unwanted files", tips: "Shift+Delete permanently deletes", os_specific: "Windows" },
            { keys: "Shift + Delete", action: "Permanent Delete", category: "File Explorer", description: "Delete without Recycle Bin", useCase: "Remove sensitive files", tips: "Cannot be recovered easily", os_specific: "Windows" },
            { keys: "Alt + Enter", action: "Properties", category: "File Explorer", description: "Open item properties", useCase: "View file details", tips: "Shows size, date, attributes", os_specific: "Windows" },
            { keys: "Ctrl + Shift + N", action: "New Folder", category: "File Explorer", description: "Create new folder", useCase: "Organize files", tips: "Name your folder immediately", os_specific: "Windows" },
            { keys: "Alt + Left Arrow", action: "Back", category: "File Explorer", description: "Go to previous folder", useCase: "Navigate back", tips: "Also works in browsers", os_specific: "Windows" },
            { keys: "Alt + Right Arrow", action: "Forward", category: "File Explorer", description: "Go to next folder", useCase: "Navigate forward", tips: "After using back button", os_specific: "Windows" },
            { keys: "Alt + Up Arrow", action: "Up One Level", category: "File Explorer", description: "Go to parent folder", useCase: "Navigate folder hierarchy", tips: "Quick parent access", os_specific: "Windows" },
            { keys: "Ctrl + W", action: "Close Tab", category: "File Explorer", description: "Close current tab", useCase: "Manage multiple tabs", tips: "Only in Windows 11", os_specific: "Windows" },
            { keys: "Ctrl + T", action: "New Tab", category: "File Explorer", description: "Open new tab", useCase: "Browse multiple folders", tips: "Only in Windows 11", os_specific: "Windows" },
            { keys: "Windows + Up Arrow", action: "Maximize Window", category: "Window Management", description: "Maximize the active window", useCase: "Fill the screen with the current app", tips: "Press again from maximized to restore in some contexts", os_specific: "Windows" },
            { keys: "Windows + Down Arrow", action: "Minimize/Restore Window", category: "Window Management", description: "Minimize the active window, or restore it if already minimized", useCase: "Quickly get a window out of the way", tips: "Press twice from maximized to minimize", os_specific: "Windows" },
            { keys: "Windows + Left Arrow", action: "Snap Window Left", category: "Window Management", description: "Snap the active window to the left half of the screen", useCase: "Side-by-side multitasking", tips: "Windows then offers the other half for a second window", os_specific: "Windows" },
            { keys: "Windows + Right Arrow", action: "Snap Window Right", category: "Window Management", description: "Snap the active window to the right half of the screen", useCase: "Side-by-side multitasking", tips: "Combine with Snap Left for a two-up layout", os_specific: "Windows" },
            { keys: "Windows + Ctrl + D", action: "New Virtual Desktop", category: "Virtual Desktops", description: "Create a new virtual desktop", useCase: "Separate work contexts", tips: "Manage desktops from Task View", os_specific: "Windows" },
            { keys: "Windows + Ctrl + Right Arrow", action: "Switch Virtual Desktop (Next)", category: "Virtual Desktops", description: "Move to the next virtual desktop", useCase: "Navigate between desktops without the mouse", tips: "Pairs with Windows+Ctrl+Left", os_specific: "Windows" }
        ]
    },

    // ==================== macOS (APPLE) SHORTCUTS ====================
    macos: {
        id: "macos",
        name: "macOS",
        platform: "mac",
        icon: "fab fa-apple",
        color: "#a0a0a0",
        description: "Complete macOS keyboard shortcuts for Finder, system navigation, and application commands",
        categories: ["Finder", "System", "Screenshots", "Text Editing", "Application", "Accessibility"],
        shortcuts: [
            { keys: "Cmd + C", action: "Copy", category: "General", description: "Copy selected items to clipboard", useCase: "Copy text or files", tips: "Works globally", os_specific: "macOS" },
            { keys: "Cmd + V", action: "Paste", category: "General", description: "Paste clipboard content", useCase: "Insert copied content", tips: "Cmd+Shift+V for plain text", os_specific: "macOS" },
            { keys: "Cmd + X", action: "Cut", category: "General", description: "Cut selected items", useCase: "Move content", tips: "Works in most apps", os_specific: "macOS" },
            { keys: "Cmd + Z", action: "Undo", category: "General", description: "Undo last action", useCase: "Revert changes", tips: "Cmd+Shift+Z for redo", os_specific: "macOS" },
            { keys: "Cmd + A", action: "Select All", category: "General", description: "Select all items", useCase: "Quick selection", tips: "Works in files and text", os_specific: "macOS" },
            { keys: "Cmd + S", action: "Save", category: "General", description: "Save current document", useCase: "Save your work", tips: "Cmd+Shift+S for Save As", os_specific: "macOS" },
            { keys: "Cmd + F", action: "Find", category: "General", description: "Search within document", useCase: "Find specific text", tips: "Cmd+G for next result", os_specific: "macOS" },
            { keys: "Cmd + Space", action: "Spotlight Search", category: "System", description: "Open Spotlight", useCase: "Search files and apps", tips: "Best way to launch apps", os_specific: "macOS" },
            { keys: "Cmd + Tab", action: "Switch Applications", category: "System", description: "Cycle through apps", useCase: "Quick app switching", tips: "Hold Cmd and press Tab", os_specific: "macOS" },
            { keys: "Cmd + Q", action: "Quit Application", category: "System", description: "Close current app", useCase: "Fully exit application", tips: "Cmd+W closes window only", os_specific: "macOS" },
            { keys: "Cmd + W", action: "Close Window", category: "System", description: "Close current window", useCase: "Close tabs/windows", tips: "Cmd+Shift+W closes all", os_specific: "macOS" },
            { keys: "Cmd + H", action: "Hide Application", category: "System", description: "Hide current app", useCase: "Declutter workspace", tips: "Cmd+Option+H hides others", os_specific: "macOS" },
            { keys: "Cmd + M", action: "Minimize Window", category: "System", description: "Minimize to Dock", useCase: "Temporarily hide window", tips: "Cmd+Option+M minimizes all", os_specific: "macOS" },
            { keys: "Cmd + N", action: "New Window", category: "General", description: "Create new window", useCase: "Open new instance", tips: "Works in most apps", os_specific: "macOS" },
            { keys: "Cmd + O", action: "Open File", category: "General", description: "Open selected file", useCase: "Open documents", tips: "From Finder or app", os_specific: "macOS" },
            { keys: "Cmd + P", action: "Print", category: "General", description: "Print current document", useCase: "Print files", tips: "Preview before printing", os_specific: "macOS" },
            { keys: "Cmd + Shift + 3", action: "Full Screenshot", category: "Screenshots", description: "Capture entire screen", useCase: "Take screenshot", tips: "Saves to desktop", os_specific: "macOS" },
            { keys: "Cmd + Shift + 4", action: "Partial Screenshot", category: "Screenshots", description: "Capture selected area", useCase: "Select area to capture", tips: "Press Space for window capture", os_specific: "macOS" },
            { keys: "Cmd + Shift + 5", action: "Screenshot Options", category: "Screenshots", description: "Open screenshot toolbar", useCase: "Choose capture mode", tips: "Screen recording also", os_specific: "macOS" },
            { keys: "Cmd + Option + Esc", action: "Force Quit", category: "System", description: "Force quit applications", useCase: "Close frozen apps", tips: "Hold for 3 seconds", os_specific: "macOS" },
            { keys: "Cmd + ,", action: "Preferences", category: "Application", description: "Open app preferences", useCase: "Configure settings", tips: "Works in most apps", os_specific: "macOS" },
            { keys: "Cmd + `", action: "Cycle Windows", category: "Application", description: "Switch between app windows", useCase: "Navigate multiple windows", tips: "Same app only", os_specific: "macOS" },
            { keys: "F3", action: "Mission Control", category: "System", description: "Open Mission Control", useCase: "View all windows", tips: "Swipe up with trackpad", os_specific: "macOS" },
            { keys: "Ctrl + Left/Right Arrow", action: "Switch Spaces", category: "System", description: "Move between desktops", useCase: "Navigate workspaces", tips: "Swipe with three fingers", os_specific: "macOS" },
            { keys: "Cmd + Delete", action: "Move to Trash", category: "Finder", description: "Move selected item to Trash", useCase: "Delete files", tips: "Cmd+Shift+Delete empties Trash", os_specific: "macOS" },
            { keys: "Cmd + Shift + Delete", action: "Empty Trash", category: "Finder", description: "Permanently delete Trash items", useCase: "Free up space", tips: "Confirmation required", os_specific: "macOS" },
            { keys: "Cmd + I", action: "Get Info", category: "Finder", description: "Show item information", useCase: "View file details", tips: "Similar to Properties", os_specific: "macOS" },
            { keys: "Cmd + D", action: "Duplicate", category: "Finder", description: "Duplicate selected item", useCase: "Create copy", tips: "Creates 'filename copy'", os_specific: "macOS" },
            { keys: "Cmd + Shift + N", action: "New Folder", category: "Finder", description: "Create new folder", useCase: "Organize files", tips: "Name immediately", os_specific: "macOS" },
            { keys: "Cmd + Up Arrow", action: "Parent Folder", category: "Finder", description: "Go to enclosing folder", useCase: "Navigate up", tips: "Cmd+Down opens item", os_specific: "macOS" },
            { keys: "Cmd + Down Arrow", action: "Open Item", category: "Finder", description: "Open selected item", useCase: "Launch files/folders", tips: "Alternative to double-click", os_specific: "macOS" },
            { keys: "Cmd + Shift + .", action: "Show Hidden Files", category: "Finder", description: "Toggle visibility of hidden files and folders in Finder", useCase: "Access dotfiles and system folders", tips: "Press again to hide them", os_specific: "macOS" },
            { keys: "Cmd + Shift + Q", action: "Log Out", category: "General", description: "Log out of the current user account", useCase: "Switch users or end your session", tips: "macOS confirms before logging out", os_specific: "macOS" },
            { keys: "Cmd + Option + D", action: "Toggle Dock", category: "General", description: "Show or hide the Dock", useCase: "Reclaim screen space", tips: "Dock still appears on hover if auto-hide is on", os_specific: "macOS" }
        ]
    },

    // ==================== LINUX/UBUNTU SHORTCUTS ====================
    linux_ubuntu: {
        id: "linux_ubuntu",
        name: "Ubuntu/Linux",
        platform: "linux",
        icon: "fab fa-linux",
        color: "#10b981",
        description: "Complete Ubuntu Linux keyboard shortcuts for terminal, desktop navigation, and applications",
        categories: ["Terminal", "Desktop", "Window Management", "Applications", "Text Editing"],
        shortcuts: [
            { keys: "Ctrl + Alt + T", action: "Open Terminal", category: "Terminal", description: "Launch terminal window", useCase: "Command line access", tips: "Quick terminal access", os_specific: "Linux" },
            { keys: "Ctrl + Shift + V", action: "Paste in Terminal", category: "Terminal", description: "Paste clipboard content", useCase: "Insert commands", tips: "Ctrl+V doesn't work in terminal", os_specific: "Linux" },
            { keys: "Ctrl + Shift + C", action: "Copy in Terminal", category: "Terminal", description: "Copy selected text", useCase: "Copy command output", tips: "Works like normal copy", os_specific: "Linux" },
            { keys: "Ctrl + L", action: "Clear Screen", category: "Terminal", description: "Clear terminal display", useCase: "Clean up workspace", tips: "Alternative to 'clear' command", os_specific: "Linux" },
            { keys: "Tab", action: "Autocomplete", category: "Terminal", description: "Auto-complete commands/paths", useCase: "Save typing", tips: "Press twice for suggestions", os_specific: "Linux" },
            { keys: "Ctrl + C", action: "Kill Process", category: "Terminal", description: "Interrupt current process", useCase: "Stop running command", tips: "Sends SIGINT signal", os_specific: "Linux" },
            { keys: "Ctrl + Z", action: "Suspend Process", category: "Terminal", description: "Suspend current process", useCase: "Pause task", tips: "Type 'fg' to resume", os_specific: "Linux" },
            { keys: "Ctrl + D", action: "Exit Terminal", category: "Terminal", description: "Close terminal session", useCase: "Log out", tips: "Alternative to 'exit'", os_specific: "Linux" },
            { keys: "Ctrl + R", action: "Search History", category: "Terminal", description: "Reverse search command history", useCase: "Find previous commands", tips: "Type to search", os_specific: "Linux" },
            { keys: "Ctrl + A", action: "Beginning of Line", category: "Terminal", description: "Move cursor to line start", useCase: "Edit command start", tips: "Home key also works", os_specific: "Linux" },
            { keys: "Ctrl + E", action: "End of Line", category: "Terminal", description: "Move cursor to line end", useCase: "Edit command end", tips: "End key also works", os_specific: "Linux" },
            { keys: "Ctrl + U", action: "Delete to Beginning", category: "Terminal", description: "Delete from cursor to line start", useCase: "Clear command", tips: "Quick way to restart", os_specific: "Linux" },
            { keys: "Ctrl + K", action: "Delete to End", category: "Terminal", description: "Delete from cursor to line end", useCase: "Remove rest of command", tips: "Keep beginning", os_specific: "Linux" },
            { keys: "Ctrl + W", action: "Delete Word", category: "Terminal", description: "Delete word behind cursor", useCase: "Remove last word", tips: "Useful for typos", os_specific: "Linux" },
            { keys: "Alt + B", action: "Back One Word", category: "Terminal", description: "Move cursor back one word", useCase: "Navigate commands", tips: "Quick navigation", os_specific: "Linux" },
            { keys: "Alt + F", action: "Forward One Word", category: "Terminal", description: "Move cursor forward one word", useCase: "Navigate commands", tips: "Quick navigation", os_specific: "Linux" },
            { keys: "Super + D", action: "Show Desktop", category: "Desktop", description: "Minimize all windows", useCase: "Access desktop", tips: "Press again to restore", os_specific: "Linux" },
            { keys: "Super + A", action: "Show Applications", category: "Desktop", description: "Open applications menu", useCase: "Launch apps", tips: "Type to search", os_specific: "Linux" },
            { keys: "Super + Tab", action: "Switch Applications", category: "Desktop", description: "Cycle through open windows", useCase: "Quick switching", tips: "Hold Super, press Tab", os_specific: "Linux" },
            { keys: "Alt + Tab", action: "Switch Windows", category: "Desktop", description: "Switch between windows", useCase: "Navigate open windows", tips: "Classic shortcut", os_specific: "Linux" },
            { keys: "Alt + F4", action: "Close Window", category: "Desktop", description: "Close current window", useCase: "Exit applications", tips: "Works everywhere", os_specific: "Linux" },
            { keys: "Ctrl + Alt + Arrow", action: "Switch Workspace", category: "Desktop", description: "Move between workspaces", useCase: "Organize work", tips: "Ctrl+Alt+Shift moves window", os_specific: "Linux" },
            { keys: "Super + S", action: "Workspace Overview", category: "Desktop", description: "Show all workspaces", useCase: "Overview mode", tips: "Click to switch", os_specific: "Linux" },
            { keys: "PrtScn", action: "Screenshot", category: "Desktop", description: "Capture entire screen", useCase: "Take screenshot", tips: "Saves to Pictures", os_specific: "Linux" },
            { keys: "Alt + PrtScn", action: "Window Screenshot", category: "Desktop", description: "Capture current window", useCase: "Screenshot window", tips: "Only active window", os_specific: "Linux" },
            { keys: "Shift + PrtScn", action: "Area Screenshot", category: "Desktop", description: "Capture selected area", useCase: "Select region", tips: "Click and drag", os_specific: "Linux" },
            { keys: "Ctrl + Alt + Del", action: "Log Out", category: "System", description: "Show logout dialog", useCase: "Log out or shutdown", tips: "Hold for system monitor", os_specific: "Linux" },
            { keys: "Ctrl + Alt + F1-F6", action: "TTY Switch", category: "System", description: "Switch to virtual console", useCase: "Recovery mode", tips: "Ctrl+Alt+F7 for GUI", os_specific: "Linux" },
            { keys: "Super", action: "Activities Overview", category: "System", description: "Open the GNOME Activities overview showing all open windows and workspaces", useCase: "See everything open at a glance", tips: "Press again or Esc to close", os_specific: "Linux" },
            { keys: "Super + L", action: "Lock Screen", category: "System", description: "Lock the screen immediately", useCase: "Secure your session when stepping away", tips: "Default GNOME lock shortcut on Ubuntu", os_specific: "Linux" },
            { keys: "Alt + F2", action: "Run Command", category: "System", description: "Open the GNOME run-command prompt", useCase: "Launch an app without a terminal", tips: "Type 'r' and Enter to restart GNOME Shell (X11 only)", os_specific: "Linux" }
        ]
    },

    // ==================== MICROSOFT OUTLOOK ====================
    outlook: {
        id: "outlook",
        name: "Microsoft Outlook",
        platform: "windows",
        icon: "fas fa-envelope",
        color: "#0078d4",
        description: "Complete Microsoft Outlook keyboard shortcuts for email, calendar, contacts, and tasks management",
        categories: ["Frequently Used", "Mail", "Calendar", "Contacts", "Navigation", "Formatting", "Search"],
        shortcuts: [
            { keys: "Ctrl + N", action: "New Email/Appointment", category: "Frequently Used", description: "Create new email message or calendar event", useCase: "Quickly compose email or schedule meeting", tips: "Works in Mail and Calendar views", os_specific: "Windows" },
            { keys: "Ctrl + R", action: "Reply to Email", category: "Frequently Used", description: "Reply to selected email sender only", useCase: "Quick response to emails", tips: "Ctrl+Shift+R for Reply All", os_specific: "Windows" },
            { keys: "Ctrl + Shift + R", action: "Reply All", category: "Frequently Used", description: "Reply to sender and all recipients", useCase: "Respond to everyone in conversation", tips: "Use carefully with large lists", os_specific: "Windows" },
            { keys: "Ctrl + F", action: "Forward Email", category: "Frequently Used", description: "Forward selected email to others", useCase: "Share emails with colleagues", tips: "Add comments before sending", os_specific: "Windows" },
            { keys: "Ctrl + Enter", action: "Send Email", category: "Frequently Used", description: "Send current email message", useCase: "Quickly send composed email", tips: "Also works in calendar invites", os_specific: "Windows" },
            { keys: "Delete", action: "Delete Item", category: "Frequently Used", description: "Move selected item to Deleted Items", useCase: "Remove unwanted emails", tips: "Shift+Delete permanently deletes", os_specific: "Windows" },
            { keys: "Ctrl + Q", action: "Mark as Read", category: "Frequently Used", description: "Mark selected message as read", useCase: "Manage email status", tips: "Ctrl+U marks as unread", os_specific: "Windows" },
            { keys: "Ctrl + U", action: "Mark as Unread", category: "Frequently Used", description: "Mark selected message as unread", useCase: "Remind to re-read later", tips: "Email appears bold again", os_specific: "Windows" },
            { keys: "Ctrl + 1", action: "Go to Mail", category: "Navigation", description: "Switch to Mail view", useCase: "Check emails", tips: "Quick navigation", os_specific: "Windows" },
            { keys: "Ctrl + 2", action: "Go to Calendar", category: "Navigation", description: "Switch to Calendar view", useCase: "Check schedule", tips: "View appointments", os_specific: "Windows" },
            { keys: "Ctrl + 3", action: "Go to Contacts", category: "Navigation", description: "Switch to People/Contacts", useCase: "Find contacts", tips: "Access address book", os_specific: "Windows" },
            { keys: "Ctrl + 4", action: "Go to Tasks", category: "Navigation", description: "Switch to Tasks/To-Do", useCase: "View tasks", tips: "Manage to-dos", os_specific: "Windows" },
            { keys: "Ctrl + E", action: "Search", category: "Search", description: "Focus search box", useCase: "Find emails quickly", tips: "Use advanced search operators", os_specific: "Windows" },
            { keys: "F9", action: "Send/Receive All", category: "Mail", description: "Sync all email accounts", useCase: "Check for new mail", tips: "Shift+F9 for current folder", os_specific: "Windows" },
            { keys: "Ctrl + Shift + M", action: "New Message Any View", category: "Mail", description: "Create new email from anywhere", useCase: "Quick compose", tips: "Global shortcut", os_specific: "Windows" },
            { keys: "Ctrl + Shift + A", action: "New Appointment", category: "Calendar", description: "Create calendar event", useCase: "Schedule meetings", tips: "Ctrl+Shift+Q for meeting request", os_specific: "Windows" },
            { keys: "Ctrl + Shift + C", action: "New Contact", category: "Contacts", description: "Create new contact", useCase: "Add person to address book", tips: "Fill in details", os_specific: "Windows" },
            { keys: "Ctrl + Shift + K", action: "New Task", category: "Tasks", description: "Create new task", useCase: "Add to-do item", tips: "Set due date", os_specific: "Windows" },
            { keys: "Ctrl + Shift + B", action: "Open Address Book", category: "Contacts", description: "Open global address list", useCase: "Find people in organization", tips: "Search for names", os_specific: "Windows" },
            { keys: "Alt + S", action: "Send Email", category: "Mail", description: "Alternative send shortcut", useCase: "Send composed email", tips: "Same as Ctrl+Enter", os_specific: "Windows" },
            { keys: "Ctrl + P", action: "Print", category: "General", description: "Open print dialog", useCase: "Print current item", tips: "Preview before printing", os_specific: "Windows" },
            { keys: "F12", action: "Save As", category: "File", description: "Save with new name", useCase: "Create copies", tips: "Choose location", os_specific: "Windows" },
            { keys: "Ctrl + W", action: "Close Window", category: "General", description: "Close current window", useCase: "Close message", tips: "Returns to previous view", os_specific: "Windows" }
        ]
    },

    // ==================== MICROSOFT EXCEL ====================
    excel: {
        id: "excel",
        name: "Microsoft Excel",
        platform: "windows",
        icon: "fas fa-table",
        color: "#217346",
        description: "Complete Microsoft Excel keyboard shortcuts for spreadsheets, formulas, data analysis, and charts",
        categories: ["Editing", "Navigation", "Formulas", "Formatting", "Data", "File", "Selection"],
        shortcuts: [
            { keys: "Ctrl + C", action: "Copy Cells", category: "Editing", description: "Copy selected cells to clipboard", useCase: "Duplicate data", tips: "Copy formatting too", os_specific: "Windows" },
            { keys: "Ctrl + V", action: "Paste Cells", category: "Editing", description: "Paste copied content", useCase: "Insert data", tips: "Ctrl+Alt+V for paste special", os_specific: "Windows" },
            { keys: "Ctrl + X", action: "Cut Cells", category: "Editing", description: "Cut selected cells", useCase: "Move data", tips: "Data removed from original", os_specific: "Windows" },
            { keys: "Ctrl + Z", action: "Undo", category: "Editing", description: "Undo last action", useCase: "Fix mistakes", tips: "Multiple undo available", os_specific: "Windows" },
            { keys: "Ctrl + Y", action: "Redo", category: "Editing", description: "Redo undone action", useCase: "Restore changes", tips: "Quick recovery", os_specific: "Windows" },
            { keys: "Ctrl + S", action: "Save Workbook", category: "File", description: "Save current file", useCase: "Save progress", tips: "F12 for Save As", os_specific: "Windows" },
            { keys: "F12", action: "Save As", category: "File", description: "Save with new name", useCase: "Create copy", tips: "Opens save dialog", os_specific: "Windows" },
            { keys: "Ctrl + O", action: "Open Workbook", category: "File", description: "Open existing file", useCase: "Open saved work", tips: "Recent files list", os_specific: "Windows" },
            { keys: "Ctrl + N", action: "New Workbook", category: "File", description: "Create new spreadsheet", useCase: "Start fresh", tips: "Blank workbook", os_specific: "Windows" },
            { keys: "F2", action: "Edit Cell", category: "Editing", description: "Edit active cell", useCase: "Modify content", tips: "Esc to cancel", os_specific: "Windows" },
            { keys: "Ctrl + Arrow", action: "Navigate to Edge", category: "Navigation", description: "Jump to data edge", useCase: "Quick navigation", tips: "Ctrl+Home to A1", os_specific: "Windows" },
            { keys: "Ctrl + Home", action: "Go to A1", category: "Navigation", description: "Jump to beginning", useCase: "Reset position", tips: "Quick navigation", os_specific: "Windows" },
            { keys: "Ctrl + End", action: "Go to Last Cell", category: "Navigation", description: "Jump to end of data", useCase: "Find bottom", tips: "Last used cell", os_specific: "Windows" },
            { keys: "Ctrl + Page Down", action: "Next Worksheet", category: "Navigation", description: "Move to next sheet", useCase: "Navigate sheets", tips: "Ctrl+Page Up for previous", os_specific: "Windows" },
            { keys: "Ctrl + Page Up", action: "Previous Worksheet", category: "Navigation", description: "Move to previous sheet", useCase: "Navigate sheets", tips: "Quick sheet switching", os_specific: "Windows" },
            { keys: "Ctrl + Space", action: "Select Column", category: "Selection", description: "Select entire column", useCase: "Format whole column", tips: "Shift+Space for row", os_specific: "Windows" },
            { keys: "Shift + Space", action: "Select Row", category: "Selection", description: "Select entire row", useCase: "Format whole row", tips: "Ctrl+Space for column", os_specific: "Windows" },
            { keys: "Ctrl + A", action: "Select All", category: "Selection", description: "Select entire worksheet", useCase: "Select everything", tips: "Press twice for all", os_specific: "Windows" },
            { keys: "Alt + =", action: "AutoSum", category: "Formulas", description: "Insert SUM formula", useCase: "Quick sum of numbers", tips: "Works on adjacent cells", os_specific: "Windows" },
            { keys: "Shift + F3", action: "Insert Function", category: "Formulas", description: "Open function wizard", useCase: "Add formula", tips: "Search for function", os_specific: "Windows" },
            { keys: "Ctrl + `", action: "Show Formulas", category: "Formulas", description: "Toggle formula view", useCase: "Debug formulas", tips: "Grave accent key", os_specific: "Windows" },
            { keys: "F4", action: "Repeat/Reference", category: "Formulas", description: "Repeat last action or cycle references", useCase: "Apply same action", tips: "Also cycles cell references", os_specific: "Windows" },
            { keys: "Ctrl + B", action: "Bold", category: "Formatting", description: "Apply bold formatting", useCase: "Emphasize text", tips: "Toggle on/off", os_specific: "Windows" },
            { keys: "Ctrl + I", action: "Italic", category: "Formatting", description: "Apply italic formatting", useCase: "Emphasize text", tips: "Toggle on/off", os_specific: "Windows" },
            { keys: "Ctrl + U", action: "Underline", category: "Formatting", description: "Apply underline", useCase: "Highlight text", tips: "Ctrl+Shift+U for double", os_specific: "Windows" },
            { keys: "Ctrl + 1", action: "Format Cells", category: "Formatting", description: "Open format cells dialog", useCase: "Number, alignment, font", tips: "All formatting options", os_specific: "Windows" },
            { keys: "Ctrl + Shift + L", action: "Toggle Filters", category: "Data", description: "Add/remove auto-filter", useCase: "Filter data", tips: "Alt+Down opens dropdown", os_specific: "Windows" },
            { keys: "Ctrl + T", action: "Create Table", category: "Data", description: "Convert to table", useCase: "Structured references", tips: "Select data first", os_specific: "Windows" },
            { keys: "Alt + F1", action: "Create Chart", category: "Charts", description: "Insert default chart", useCase: "Quick visualization", tips: "Select data first", os_specific: "Windows" },
            { keys: "F11", action: "Chart Sheet", category: "Charts", description: "Create chart in new sheet", useCase: "Separate chart", tips: "Dedicated chart tab", os_specific: "Windows" },
            { keys: "Ctrl + D", action: "Fill Down", category: "Editing", description: "Copy from cell above", useCase: "Copy formula down", tips: "Select range first", os_specific: "Windows" },
            { keys: "Ctrl + R", action: "Fill Right", category: "Editing", description: "Copy from left cell", useCase: "Copy formula right", tips: "Select range first", os_specific: "Windows" },
            { keys: "Alt + Enter", action: "New Line in Cell", category: "Editing", description: "Add line break", useCase: "Multi-line text", tips: "Wrap text must be on", os_specific: "Windows" },
            { keys: "Ctrl + ;", action: "Current Date", category: "Data Entry", description: "Insert today's date", useCase: "Date stamp", tips: "Static date", os_specific: "Windows" },
            { keys: "Ctrl + Shift + ;", action: "Current Time", category: "Data Entry", description: "Insert current time", useCase: "Time stamp", tips: "Static time", os_specific: "Windows" },
            { keys: "Ctrl + K", action: "Insert Hyperlink", category: "Insert", description: "Add hyperlink", useCase: "Link to websites", tips: "Select cell first", os_specific: "Windows" },
            { keys: "Shift + F11", action: "New Worksheet", category: "Worksheet", description: "Insert new sheet", useCase: "Add worksheet", tips: "Quick addition", os_specific: "Windows" },
            { keys: "F9", action: "Recalculate Workbook", category: "Formulas", description: "Force Excel to recalculate all formulas in the workbook", useCase: "Refresh results after switching to manual calculation mode", tips: "Shift+F9 recalculates only the active sheet", os_specific: "Windows" },
            { keys: "Ctrl + 9", action: "Hide Rows", category: "Formatting", description: "Hide the selected rows", useCase: "Temporarily declutter a sheet", tips: "Ctrl+Shift+9 unhides rows", os_specific: "Windows" },
            { keys: "Ctrl + 0", action: "Hide Columns", category: "Formatting", description: "Hide the selected columns", useCase: "Temporarily declutter a sheet", tips: "Ctrl+Shift+0 unhides columns", os_specific: "Windows" },
            { keys: "Ctrl + Shift + End", action: "Select to Last Used Cell", category: "Selection", description: "Extend the selection from the active cell to the last used cell", useCase: "Select an entire data range quickly", tips: "Pairs with Ctrl+Shift+Home", os_specific: "Windows" },
            { keys: "Ctrl + Shift + Home", action: "Select to A1", category: "Selection", description: "Extend the selection from the active cell back to cell A1", useCase: "Select from your position to the top of the sheet", tips: "Pairs with Ctrl+Shift+End", os_specific: "Windows" }
        ]
    },

    // ==================== MICROSOFT WORD ====================
    word: {
        id: "word",
        name: "Microsoft Word",
        platform: "windows",
        icon: "fas fa-file-word",
        color: "#185abD",
        description: "Complete Microsoft Word keyboard shortcuts for document editing, formatting, and review",
        categories: ["Editing", "Formatting", "Navigation", "File", "Review", "Tables"],
        shortcuts: [
            { keys: "Ctrl + N", action: "New Document", category: "File", description: "Create new blank document", useCase: "Start new file", tips: "Ctrl+Shift+N for new", os_specific: "Windows" },
            { keys: "Ctrl + O", action: "Open Document", category: "File", description: "Open existing document", useCase: "Open saved file", tips: "Recent files list", os_specific: "Windows" },
            { keys: "Ctrl + S", action: "Save Document", category: "File", description: "Save current document", useCase: "Save progress", tips: "Save frequently", os_specific: "Windows" },
            { keys: "F12", action: "Save As", category: "File", description: "Save with new name", useCase: "Create copy", tips: "Choose format", os_specific: "Windows" },
            { keys: "Ctrl + P", action: "Print", category: "File", description: "Open print dialog", useCase: "Print document", tips: "Preview before printing", os_specific: "Windows" },
            { keys: "Ctrl + W", action: "Close Document", category: "File", description: "Close current document", useCase: "Close file", tips: "Save if needed", os_specific: "Windows" },
            { keys: "Ctrl + Z", action: "Undo", category: "Editing", description: "Undo last action", useCase: "Fix mistakes", tips: "Multiple undo", os_specific: "Windows" },
            { keys: "Ctrl + Y", action: "Redo", category: "Editing", description: "Redo undone action", useCase: "Restore changes", tips: "Ctrl+Shift+Z also works", os_specific: "Windows" },
            { keys: "Ctrl + X", action: "Cut", category: "Editing", description: "Cut selected text", useCase: "Move content", tips: "Content to clipboard", os_specific: "Windows" },
            { keys: "Ctrl + C", action: "Copy", category: "Editing", description: "Copy selected text", useCase: "Duplicate content", tips: "Preserves formatting", os_specific: "Windows" },
            { keys: "Ctrl + V", action: "Paste", category: "Editing", description: "Paste clipboard content", useCase: "Insert content", tips: "Ctrl+Shift+V for plain text", os_specific: "Windows" },
            { keys: "Ctrl + A", action: "Select All", category: "Editing", description: "Select entire document", useCase: "Select everything", tips: "Works everywhere", os_specific: "Windows" },
            { keys: "Ctrl + F", action: "Find", category: "Editing", description: "Open find dialog", useCase: "Search text", tips: "Ctrl+H for replace", os_specific: "Windows" },
            { keys: "Ctrl + H", action: "Replace", category: "Editing", description: "Find and replace", useCase: "Replace text", tips: "Replace all option", os_specific: "Windows" },
            { keys: "Ctrl + B", action: "Bold", category: "Formatting", description: "Apply bold formatting", useCase: "Emphasize text", tips: "Toggle on/off", os_specific: "Windows" },
            { keys: "Ctrl + I", action: "Italic", category: "Formatting", description: "Apply italic formatting", useCase: "Emphasize text", tips: "Toggle on/off", os_specific: "Windows" },
            { keys: "Ctrl + U", action: "Underline", category: "Formatting", description: "Apply underline", useCase: "Highlight text", tips: "Ctrl+Shift+W for word only", os_specific: "Windows" },
            { keys: "Ctrl + E", action: "Center Align", category: "Formatting", description: "Center paragraph", useCase: "Center titles", tips: "Works on paragraphs", os_specific: "Windows" },
            { keys: "Ctrl + L", action: "Left Align", category: "Formatting", description: "Left align paragraph", useCase: "Default alignment", tips: "Most common", os_specific: "Windows" },
            { keys: "Ctrl + R", action: "Right Align", category: "Formatting", description: "Right align paragraph", useCase: "Align dates", tips: "Use sparingly", os_specific: "Windows" },
            { keys: "Ctrl + J", action: "Justify", category: "Formatting", description: "Justify paragraph", useCase: "Newspaper style", tips: "Even margins", os_specific: "Windows" },
            { keys: "Ctrl + M", action: "Indent", category: "Formatting", description: "Increase indent", useCase: "Indent paragraph", tips: "Ctrl+Shift+M to decrease", os_specific: "Windows" },
            { keys: "Ctrl + Shift + <", action: "Decrease Font", category: "Formatting", description: "Decrease font size", useCase: "Make text smaller", tips: "Press repeatedly", os_specific: "Windows" },
            { keys: "Ctrl + Shift + >", action: "Increase Font", category: "Formatting", description: "Increase font size", useCase: "Make text larger", tips: "Press repeatedly", os_specific: "Windows" },
            { keys: "Ctrl + D", action: "Font Dialog", category: "Formatting", description: "Open font options", useCase: "All formatting", tips: "Advanced options", os_specific: "Windows" },
            { keys: "Ctrl + K", action: "Insert Hyperlink", category: "Insert", description: "Add hyperlink", useCase: "Link to web", tips: "Select text first", os_specific: "Windows" },
            { keys: "Ctrl + Enter", action: "Page Break", category: "Insert", description: "Insert page break", useCase: "New page", tips: "Quick page break", os_specific: "Windows" },
            { keys: "Home", action: "Line Start", category: "Navigation", description: "Go to line beginning", useCase: "Quick navigation", tips: "Ctrl+Home for document", os_specific: "Windows" },
            { keys: "End", action: "Line End", category: "Navigation", description: "Go to line end", useCase: "Quick navigation", tips: "Ctrl+End for document", os_specific: "Windows" },
            { keys: "Ctrl + Home", action: "Document Start", category: "Navigation", description: "Go to beginning", useCase: "Top of document", tips: "Quick navigation", os_specific: "Windows" },
            { keys: "Ctrl + End", action: "Document End", category: "Navigation", description: "Go to end", useCase: "Bottom of document", tips: "Quick navigation", os_specific: "Windows" },
            { keys: "F7", action: "Spell Check", category: "Review", description: "Check spelling", useCase: "Proofread", tips: "Review suggestions", os_specific: "Windows" },
            { keys: "Shift + F7", action: "Thesaurus", category: "Review", description: "Open thesaurus", useCase: "Find synonyms", tips: "Select word first", os_specific: "Windows" },
            { keys: "Alt + Shift + D", action: "Insert Date", category: "Insert", description: "Insert current date", useCase: "Date stamp", tips: "Updates automatically", os_specific: "Windows" },
            { keys: "Alt + Shift + T", action: "Insert Time", category: "Insert", description: "Insert current time", useCase: "Time stamp", tips: "Updates automatically", os_specific: "Windows" }
        ]
    },

    // ==================== MICROSOFT POWERPOINT ====================
    powerpoint: {
        id: "powerpoint",
        name: "Microsoft PowerPoint",
        platform: "windows",
        icon: "fas fa-chalkboard",
        color: "#d35230",
        description: "Complete Microsoft PowerPoint keyboard shortcuts for creating and delivering presentations",
        categories: ["Presentation", "Editing", "Formatting", "Navigation", "Slides", "Objects"],
        shortcuts: [
            { keys: "F5", action: "Start Slideshow", category: "Presentation", description: "Begin presentation from start", useCase: "Present to audience", tips: "Shift+F5 from current slide", os_specific: "Windows" },
            { keys: "Shift + F5", action: "From Current Slide", category: "Presentation", description: "Start from current slide", useCase: "Continue presentation", tips: "Quick resume", os_specific: "Windows" },
            { keys: "Esc", action: "End Slideshow", category: "Presentation", description: "Exit presentation mode", useCase: "Stop presenting", tips: "Returns to editor", os_specific: "Windows" },
            { keys: "N", action: "Next Slide", category: "Presentation", description: "Go to next slide", useCase: "Advance presentation", tips: "Also Enter, Space, Right Arrow", os_specific: "Windows" },
            { keys: "P", action: "Previous Slide", category: "Presentation", description: "Go to previous slide", useCase: "Go back", tips: "Also Backspace, Left Arrow", os_specific: "Windows" },
            { keys: "Ctrl + N", action: "New Presentation", category: "File", description: "Create new presentation", useCase: "Start fresh", tips: "Blank presentation", os_specific: "Windows" },
            { keys: "Ctrl + O", action: "Open Presentation", category: "File", description: "Open existing file", useCase: "Open saved work", tips: "Recent files", os_specific: "Windows" },
            { keys: "Ctrl + S", action: "Save", category: "File", description: "Save presentation", useCase: "Save progress", tips: "Save frequently", os_specific: "Windows" },
            { keys: "Ctrl + M", action: "New Slide", category: "Slides", description: "Insert new slide", useCase: "Add content", tips: "Ctrl+D duplicates", os_specific: "Windows" },
            { keys: "Ctrl + D", action: "Duplicate Slide", category: "Slides", description: "Copy selected slide", useCase: "Reuse layout", tips: "Quick duplication", os_specific: "Windows" },
            { keys: "Delete", action: "Delete Slide", category: "Slides", description: "Remove selected slide", useCase: "Remove content", tips: "Cannot undo if closed", os_specific: "Windows" },
            { keys: "Ctrl + B", action: "Bold", category: "Formatting", description: "Apply bold formatting", useCase: "Emphasize text", tips: "Toggle on/off", os_specific: "Windows" },
            { keys: "Ctrl + I", action: "Italic", category: "Formatting", description: "Apply italic formatting", useCase: "Emphasize text", tips: "Toggle on/off", os_specific: "Windows" },
            { keys: "Ctrl + U", action: "Underline", category: "Formatting", description: "Apply underline", useCase: "Highlight text", tips: "Toggle on/off", os_specific: "Windows" },
            { keys: "Ctrl + G", action: "Group Objects", category: "Objects", description: "Group selected objects", useCase: "Move together", tips: "Ctrl+Shift+G to ungroup", os_specific: "Windows" },
            { keys: "Ctrl + Shift + G", action: "Ungroup", category: "Objects", description: "Ungroup objects", useCase: "Edit individually", tips: "Select group first", os_specific: "Windows" },
            { keys: "Ctrl + K", action: "Insert Hyperlink", category: "Insert", description: "Add hyperlink", useCase: "Link to web", tips: "Select text first", os_specific: "Windows" },
            { keys: "Ctrl + 1", action: "Normal View", category: "View", description: "Switch to normal view", useCase: "Edit slides", tips: "Default view", os_specific: "Windows" },
            { keys: "Ctrl + =", action: "Zoom In", category: "View", description: "Zoom in", useCase: "Magnify content", tips: "Ctrl+- to zoom out", os_specific: "Windows" },
            { keys: "Ctrl + -", action: "Zoom Out", category: "View", description: "Zoom out", useCase: "See more", tips: "Ctrl+0 for fit", os_specific: "Windows" }
        ]
    },

    // ==================== FIGMA ====================
    figma: {
        id: "figma",
        name: "Figma",
        platform: "windows",
        icon: "fab fa-figma",
        color: "#0acf83",
        description: "Complete Figma keyboard shortcuts for UI/UX design, prototyping, and collaboration",
        categories: ["Tools", "Layers", "Text", "Vector", "Prototyping", "Components", "View"],
        shortcuts: [
            { keys: "V", action: "Move Tool", category: "Tools", description: "Select and move objects", useCase: "Navigate and select", tips: "Most used tool", os_specific: "Windows" },
            { keys: "F", action: "Frame Tool", category: "Tools", description: "Create frames", useCase: "Design containers", tips: "Shift+F for slice tool", os_specific: "Windows" },
            { keys: "R", action: "Rectangle Tool", category: "Tools", description: "Draw rectangles", useCase: "Create shapes", tips: "Hold Shift for square", os_specific: "Windows" },
            { keys: "O", action: "Ellipse Tool", category: "Tools", description: "Draw circles/ellipses", useCase: "Create round shapes", tips: "Hold Shift for perfect circle", os_specific: "Windows" },
            { keys: "T", action: "Text Tool", category: "Tools", description: "Add text", useCase: "Typography", tips: "Double-click to edit", os_specific: "Windows" },
            { keys: "H", action: "Hand Tool", category: "Tools", description: "Pan canvas", useCase: "Navigate around", tips: "Hold Spacebar temporarily", os_specific: "Windows" },
            { keys: "Ctrl + +", action: "Zoom In", category: "View", description: "Magnify view", useCase: "See details", tips: "Hold Z for zoom tool", os_specific: "Windows" },
            { keys: "Ctrl + -", action: "Zoom Out", category: "View", description: "Reduce view", useCase: "See more", tips: "Hold Alt+Z for zoom out", os_specific: "Windows" },
            { keys: "Ctrl + 0", action: "Zoom to 100%", category: "View", description: "Actual size", useCase: "See real pixels", tips: "Double-click zoom tool", os_specific: "Windows" },
            { keys: "Shift + 1", action: "Zoom to Fit", category: "View", description: "Fit to screen", useCase: "See entire design", tips: "Double-click hand tool", os_specific: "Windows" },
            { keys: "Shift + R", action: "Show/Hide Rulers", category: "View", description: "Toggle rulers", useCase: "Measure distances", tips: "Drag from rulers for guides", os_specific: "Windows" },
            { keys: "Shift + G", action: "Show/Hide Grids", category: "View", description: "Toggle layout grids", useCase: "Align elements", tips: "Customize grid spacing", os_specific: "Windows" },
            { keys: "Ctrl + R", action: "Rename Layer", category: "Layers", description: "Rename selected layer", useCase: "Organize layers", tips: "Use descriptive names", os_specific: "Windows" },
            { keys: "Enter", action: "Select Children", category: "Layers", description: "Select nested objects", useCase: "Deep selection", tips: "Drill into groups", os_specific: "Windows" },
            { keys: "Tab", action: "Next Sibling", category: "Layers", description: "Select next layer", useCase: "Navigate layers", tips: "Shift+Tab for previous", os_specific: "Windows" },
            { keys: "Esc", action: "Deselect", category: "Layers", description: "Clear selection", useCase: "Start over", tips: "Quick unselect", os_specific: "Windows" },
            { keys: "Ctrl + G", action: "Group Selection", category: "Layers", description: "Group selected layers", useCase: "Organize together", tips: "Ctrl+Shift+G to ungroup", os_specific: "Windows" },
            { keys: "Shift + A", action: "Auto Layout", category: "Layout", description: "Add auto layout frame", useCase: "Responsive designs", tips: "Great for components", os_specific: "Windows" },
            { keys: "[", action: "Send to Back", category: "Arrange", description: "Move layer to back", useCase: "Stack ordering", tips: "Layer hierarchy", os_specific: "Windows" },
            { keys: "]", action: "Bring to Front", category: "Arrange", description: "Move layer to front", useCase: "Stack ordering", tips: "Top layer", os_specific: "Windows" },
            { keys: "Alt + A", action: "Align Left", category: "Align", description: "Align left edges", useCase: "Organize layout", tips: "Select multiple objects", os_specific: "Windows" },
            { keys: "Alt + D", action: "Align Right", category: "Align", description: "Align right edges", useCase: "Organize layout", tips: "Select multiple objects", os_specific: "Windows" },
            { keys: "Alt + W", action: "Align Top", category: "Align", description: "Align top edges", useCase: "Organize layout", tips: "Select multiple objects", os_specific: "Windows" },
            { keys: "Alt + S", action: "Align Bottom", category: "Align", description: "Align bottom edges", useCase: "Organize layout", tips: "Select multiple objects", os_specific: "Windows" },
            { keys: "Alt + H", action: "Align Center Horizontal", category: "Align", description: "Center horizontally", useCase: "Perfect centering", tips: "Within selection", os_specific: "Windows" },
            { keys: "Alt + V", action: "Align Center Vertical", category: "Align", description: "Center vertically", useCase: "Perfect centering", tips: "Within selection", os_specific: "Windows" },
            { keys: "Ctrl + D", action: "Duplicate", category: "Editing", description: "Duplicate selection", useCase: "Copy objects", tips: "Alt+Drag also works", os_specific: "Windows" },
            { keys: "Ctrl + Shift + <", action: "Decrease Font Size", category: "Text", description: "Smaller text", useCase: "Adjust typography", tips: "1px increments", os_specific: "Windows" },
            { keys: "Ctrl + Shift + >", action: "Increase Font Size", category: "Text", description: "Larger text", useCase: "Adjust typography", tips: "1px increments", os_specific: "Windows" },
            { keys: "Ctrl + B", action: "Bold", category: "Text", description: "Apply bold", useCase: "Emphasize text", tips: "Toggle on/off", os_specific: "Windows" },
            { keys: "Ctrl + I", action: "Italic", category: "Text", description: "Apply italic", useCase: "Emphasize text", tips: "Toggle on/off", os_specific: "Windows" },
            { keys: "Ctrl + U", action: "Underline", category: "Text", description: "Apply underline", useCase: "Highlight text", tips: "Toggle on/off", os_specific: "Windows" },
            { keys: "Ctrl + Alt + K", action: "Create Component", category: "Components", description: "Create reusable component", useCase: "Design systems", tips: "Use instances", os_specific: "Windows" },
            { keys: "Shift + I", action: "Insert Instance", category: "Components", description: "Place component instance", useCase: "Use components", tips: "Browse components", os_specific: "Windows" },
            { keys: "Ctrl + Alt + B", action: "Detach Instance", category: "Components", description: "Break component link", useCase: "Customize instance", tips: "No longer updates", os_specific: "Windows" },
            { keys: "Ctrl + Alt + Enter", action: "Present Prototype", category: "Prototyping", description: "Open presentation view", useCase: "Demo designs", tips: "New window", os_specific: "Windows" },
            { keys: "Ctrl + Shift + E", action: "Export", category: "File", description: "Open export dialog", useCase: "Export assets", tips: "Multiple formats", os_specific: "Windows" },
            { keys: "Ctrl + F", action: "Find", category: "General", description: "Search in file", useCase: "Find layers/text", tips: "Type to search", os_specific: "Windows" }
        ]
    },

    // ==================== VS CODE ====================
    vscode: {
        id: "vscode",
        name: "VS Code",
        platform: "windows",
        icon: "fab fa-windows",
        color: "#007acc",
        description: "Complete Visual Studio Code keyboard shortcuts for coding, debugging, and productivity",
        categories: ["General", "Editing", "Navigation", "Search", "Debug", "Terminal", "Display"],
        shortcuts: [
            { keys: "Ctrl + Shift + P", action: "Command Palette", category: "General", description: "Open all commands", useCase: "Access any feature", tips: "Most important shortcut", os_specific: "Windows" },
            { keys: "Ctrl + P", action: "Quick Open", category: "General", description: "Go to file", useCase: "Open files quickly", tips: "Type filename", os_specific: "Windows" },
            { keys: "Ctrl + Shift + N", action: "New Window", category: "General", description: "Open new window", useCase: "Multi-project work", tips: "Separate instance", os_specific: "Windows" },
            { keys: "Ctrl + W", action: "Close Editor", category: "General", description: "Close the active editor tab", useCase: "Close current file", tips: "Reopen with Ctrl+Shift+T", os_specific: "Windows" },
            { keys: "Ctrl + ,", action: "User Settings", category: "General", description: "Open settings", useCase: "Configure VS Code", tips: "JSON or UI", os_specific: "Windows" },
            { keys: "Ctrl + X", action: "Cut Line", category: "Editing", description: "Cut current line", useCase: "Move code", tips: "No selection needed", os_specific: "Windows" },
            { keys: "Ctrl + C", action: "Copy Line", category: "Editing", description: "Copy current line", useCase: "Duplicate code", tips: "No selection needed", os_specific: "Windows" },
            { keys: "Alt + Up/Down", action: "Move Line", category: "Editing", description: "Move line up/down", useCase: "Reorder code", tips: "Quick rearrangement", os_specific: "Windows" },
            { keys: "Shift + Alt + Up/Down", action: "Copy Line Up/Down", category: "Editing", description: "Duplicate line", useCase: "Copy code quickly", tips: "Creates copy", os_specific: "Windows" },
            { keys: "Ctrl + Shift + K", action: "Delete Line", category: "Editing", description: "Delete current line", useCase: "Remove code", tips: "No selection needed", os_specific: "Windows" },
            { keys: "Ctrl + Enter", action: "Insert Line Below", category: "Editing", description: "Add line below", useCase: "New line", tips: "Current position", os_specific: "Windows" },
            { keys: "Ctrl + Shift + Enter", action: "Insert Line Above", category: "Editing", description: "Add line above", useCase: "Insert before", tips: "Current position", os_specific: "Windows" },
            { keys: "Ctrl + ]", action: "Indent", category: "Editing", description: "Increase indent", useCase: "Format code", tips: "Select lines first", os_specific: "Windows" },
            { keys: "Ctrl + [", action: "Outdent", category: "Editing", description: "Decrease indent", useCase: "Format code", tips: "Select lines first", os_specific: "Windows" },
            { keys: "Home", action: "Line Start", category: "Navigation", description: "Go to beginning of line", useCase: "Quick navigation", tips: "Press again for start", os_specific: "Windows" },
            { keys: "End", action: "Line End", category: "Navigation", description: "Go to end of line", useCase: "Quick navigation", tips: "End of line", os_specific: "Windows" },
            { keys: "Ctrl + Home", action: "File Start", category: "Navigation", description: "Go to beginning of file", useCase: "Top of file", tips: "Quick jump", os_specific: "Windows" },
            { keys: "Ctrl + End", action: "File End", category: "Navigation", description: "Go to end of file", useCase: "Bottom of file", tips: "Quick jump", os_specific: "Windows" },
            { keys: "Ctrl + /", action: "Toggle Line Comment", category: "Editing", description: "Comment/uncomment line", useCase: "Disable code", tips: "Select lines first", os_specific: "Windows" },
            { keys: "Shift + Alt + A", action: "Toggle Block Comment", category: "Editing", description: "Add/remove block comment", useCase: "Multi-line comments", tips: "/* */ style", os_specific: "Windows" },
            { keys: "Ctrl + F", action: "Find", category: "Search", description: "Open find widget", useCase: "Search in file", tips: "Type to search", os_specific: "Windows" },
            { keys: "Ctrl + H", action: "Replace", category: "Search", description: "Open replace widget", useCase: "Find and replace", tips: "All at once", os_specific: "Windows" },
            { keys: "F3", action: "Find Next", category: "Search", description: "Go to next match", useCase: "Navigate results", tips: "Shift+F3 for previous", os_specific: "Windows" },
            { keys: "Ctrl + Shift + F", action: "Find in Files", category: "Search", description: "Search across project", useCase: "Global search", tips: "Include/exclude files", os_specific: "Windows" },
            { keys: "Ctrl + T", action: "Show All Symbols", category: "Navigation", description: "Search symbols", useCase: "Find functions/classes", tips: "Type to filter", os_specific: "Windows" },
            { keys: "Ctrl + G", action: "Go to Line", category: "Navigation", description: "Jump to line number", useCase: "Specific line", tips: "Type line number", os_specific: "Windows" },
            { keys: "F8", action: "Next Error/Warning", category: "Navigation", description: "Go to next problem", useCase: "Fix errors", tips: "Shift+F8 for previous", os_specific: "Windows" },
            { keys: "Ctrl + Space", action: "Trigger Suggestion", category: "IntelliSense", description: "Show code suggestions", useCase: "Auto-complete", tips: "Context-aware", os_specific: "Windows" },
            { keys: "Shift + Alt + F", action: "Format Document", category: "Formatting", description: "Format entire file", useCase: "Auto-format code", tips: "Uses prettier/formatter", os_specific: "Windows" },
            { keys: "F12", action: "Go to Definition", category: "Navigation", description: "Jump to definition", useCase: "Explore code", tips: "Ctrl+click also works", os_specific: "Windows" },
            { keys: "Ctrl + .", action: "Quick Fix", category: "Refactoring", description: "Show code actions", useCase: "Fix errors", tips: "Lightbulb menu", os_specific: "Windows" },
            { keys: "F2", action: "Rename Symbol", category: "Refactoring", description: "Rename symbol across files", useCase: "Safe renaming", tips: "Updates all references", os_specific: "Windows" },
            { keys: "Ctrl + \\", action: "Split Editor", category: "Editor", description: "Split editor window", useCase: "Multi-file view", tips: "Side by side", os_specific: "Windows" },
            { keys: "Ctrl + B", action: "Toggle Sidebar", category: "Display", description: "Show/hide sidebar", useCase: "More editor space", tips: "Maximize coding", os_specific: "Windows" },
            { keys: "Ctrl + `", action: "Toggle Terminal", category: "Terminal", description: "Open integrated terminal", useCase: "Run commands", tips: "Ctrl+Shift+` for new", os_specific: "Windows" },
            { keys: "F9", action: "Toggle Breakpoint", category: "Debug", description: "Add/remove breakpoint", useCase: "Pause execution", tips: "Red dot appears", os_specific: "Windows" },
            { keys: "F5", action: "Start/Continue", category: "Debug", description: "Start debugging or continue", useCase: "Run code", tips: "Stops at breakpoints", os_specific: "Windows" },
            { keys: "Shift + F5", action: "Stop", category: "Debug", description: "Stop debugging", useCase: "End debug session", tips: "Terminates", os_specific: "Windows" },
            { keys: "F10", action: "Step Over", category: "Debug", description: "Execute next line", useCase: "Skip function details", tips: "Don't enter functions", os_specific: "Windows" },
            { keys: "F11", action: "Step Into", category: "Debug", description: "Enter function", useCase: "Debug inside", tips: "Go into functions", os_specific: "Windows" },
            { keys: "Shift + F11", action: "Step Out", category: "Debug", description: "Exit current function", useCase: "Return to caller", tips: "Complete current", os_specific: "Windows" },
            { keys: "Ctrl + N", action: "New File", category: "General", description: "Create a new untitled file", useCase: "Start a new file quickly", tips: "Save with Ctrl+S to name it", os_specific: "Windows" },
            { keys: "Ctrl + S", action: "Save", category: "General", description: "Save the active file", useCase: "Persist your changes", tips: "Enable Auto Save to skip this", os_specific: "Windows" },
            { keys: "Ctrl + K S", action: "Save All", category: "General", description: "Save every open, unsaved file", useCase: "Save all tabs before running/building", tips: "Press Ctrl+K then S", os_specific: "Windows" },
            { keys: "Ctrl + Shift + T", action: "Reopen Closed Editor", category: "General", description: "Reopen the most recently closed tab", useCase: "Undo an accidental tab close", tips: "Press repeatedly to reopen more", os_specific: "Windows" },
            { keys: "Ctrl + K Ctrl + W", action: "Close All Editors", category: "General", description: "Close every open editor tab", useCase: "Clear your workspace", tips: "Press Ctrl+K then Ctrl+W", os_specific: "Windows" },
            { keys: "Ctrl + Shift + O", action: "Go to Symbol in File", category: "Navigation", description: "Jump to a function, class, or variable in the current file", useCase: "Navigate large files fast", tips: "Type @ then a symbol name", os_specific: "Windows" },
            { keys: "Alt + F12", action: "Peek Definition", category: "Navigation", description: "Show a definition inline without leaving the current file", useCase: "Check a function's implementation quickly", tips: "Esc to close the peek view", os_specific: "Windows" },
            { keys: "Shift + F12", action: "Go to References", category: "Navigation", description: "List everywhere a symbol is used", useCase: "Find all usages before renaming or removing code", tips: "Opens a references panel", os_specific: "Windows" },
            { keys: "Shift + Alt + O", action: "Organize Imports", category: "Editing", description: "Sort and clean up import statements", useCase: "Tidy imports before committing", tips: "Language-server dependent", os_specific: "Windows" },
            { keys: "Ctrl + D", action: "Add Selection to Next Find Match", category: "Editing", description: "Select the next occurrence of the current word for multi-cursor editing", useCase: "Rename several matches at once", tips: "Keep pressing to add more", os_specific: "Windows" },
            { keys: "Ctrl + Shift + L", action: "Select All Occurrences", category: "Editing", description: "Select every occurrence of the current selection at once", useCase: "Bulk-edit repeated text", tips: "Great with Ctrl+D for a preview first", os_specific: "Windows" },
            { keys: "Ctrl + Alt + Up/Down", action: "Insert Cursor Above/Below", category: "Editing", description: "Add an additional cursor on the line above or below", useCase: "Edit multiple lines at once", tips: "Esc to return to a single cursor", os_specific: "Windows" },
            { keys: "Ctrl + K Ctrl + 0", action: "Fold All", category: "Editing", description: "Collapse all foldable regions in the file", useCase: "Get a high-level view of a large file", tips: "Press Ctrl+K then Ctrl+0", os_specific: "Windows" },
            { keys: "Ctrl + K Ctrl + J", action: "Unfold All", category: "Editing", description: "Expand all folded regions", useCase: "Restore full file view", tips: "Press Ctrl+K then Ctrl+J", os_specific: "Windows" },
            { keys: "Ctrl + Shift + [", action: "Fold Region", category: "Editing", description: "Collapse the current code block", useCase: "Hide a function or block temporarily", tips: "Cursor must be inside the region", os_specific: "Windows" },
            { keys: "Ctrl + Shift + ]", action: "Unfold Region", category: "Editing", description: "Expand the current collapsed block", useCase: "Reveal hidden code", tips: "Cursor must be inside the region", os_specific: "Windows" },
            { keys: "Ctrl + Shift + E", action: "Show Explorer", category: "Display", description: "Open the file explorer sidebar", useCase: "Browse project files", tips: "Toggles the sidebar focus", os_specific: "Windows" },
            { keys: "Ctrl + Shift + G", action: "Show Source Control", category: "Display", description: "Open the Git source control panel", useCase: "Stage, commit, and review changes", tips: "Requires a Git repository", os_specific: "Windows" },
            { keys: "Ctrl + Shift + M", action: "Show Problems Panel", category: "Display", description: "Open the panel listing errors and warnings", useCase: "Review lint/compile issues", tips: "Also toggles the panel view", os_specific: "Windows" },
            { keys: "Ctrl + J", action: "Toggle Panel", category: "Display", description: "Show or hide the bottom panel (terminal, problems, output)", useCase: "Reclaim screen space while coding", tips: "Panel remembers its last tab", os_specific: "Windows" },
            { keys: "Ctrl + Shift + `", action: "New Terminal", category: "Terminal", description: "Open a new integrated terminal instance", useCase: "Run a second command alongside another", tips: "Creates an additional terminal tab", os_specific: "Windows" },
            { keys: "Ctrl + K Z", action: "Zen Mode", category: "Display", description: "Hide all UI chrome for a distraction-free, full-screen editor", useCase: "Focus writing or reviewing code", tips: "Press Esc twice to exit", os_specific: "Windows" }
        ]
    },

    // ==================== WEB BROWSERS ====================
    browsers: {
        id: "browsers",
        name: "Web Browsers",
        platform: "windows",
        icon: "fab fa-chrome",
        color: "#4285f4",
        description: "Common keyboard shortcuts for web browsers (Chrome, Edge, Firefox)",
        categories: ["Tabs", "Navigation", "Bookmarks", "Page", "History", "Developer"],
        shortcuts: [
            { keys: "Ctrl + T", action: "New Tab", category: "Tabs", description: "Open new tab", useCase: "Browse multiple pages", tips: "Ctrl+Shift+T reopens closed", os_specific: "Windows" },
            { keys: "Ctrl + W", action: "Close Tab", category: "Tabs", description: "Close current tab", useCase: "Remove unwanted tabs", tips: "Ctrl+Shift+W closes window", os_specific: "Windows" },
            { keys: "Ctrl + Shift + T", action: "Reopen Closed Tab", category: "Tabs", description: "Restore last closed tab", useCase: "Recover accidentally closed", tips: "Press repeatedly for more", os_specific: "Windows" },
            { keys: "Ctrl + Tab", action: "Next Tab", category: "Tabs", description: "Switch to next tab", useCase: "Navigate tabs", tips: "Ctrl+Shift+Tab for previous", os_specific: "Windows" },
            { keys: "Ctrl + Shift + Tab", action: "Previous Tab", category: "Tabs", description: "Switch to previous tab", useCase: "Navigate tabs", tips: "Reverse order", os_specific: "Windows" },
            { keys: "Ctrl + 1-8", action: "Go to Tab Number", category: "Tabs", description: "Jump to specific tab", useCase: "Quick access", tips: "Ctrl+1 for first tab", os_specific: "Windows" },
            { keys: "Ctrl + 9", action: "Go to Last Tab", category: "Tabs", description: "Jump to last tab", useCase: "End of tab bar", tips: "Most right tab", os_specific: "Windows" },
            { keys: "Ctrl + N", action: "New Window", category: "Window", description: "Open new browser window", useCase: "Separate browsing", tips: "New session", os_specific: "Windows" },
            { keys: "Ctrl + Shift + N", action: "New Incognito/Private", category: "Window", description: "Open private window", useCase: "Private browsing", tips: "No history saved", os_specific: "Windows" },
            { keys: "Ctrl + L", action: "Focus Address Bar", category: "Navigation", description: "Select URL bar", useCase: "Type new URL", tips: "F6 also works", os_specific: "Windows" },
            { keys: "Ctrl + D", action: "Bookmark Page", category: "Bookmarks", description: "Save current page", useCase: "Save for later", tips: "Ctrl+Shift+D bookmarks all", os_specific: "Windows" },
            { keys: "Ctrl + H", action: "History", category: "History", description: "View browsing history", useCase: "Find visited pages", tips: "Ctrl+J for downloads", os_specific: "Windows" },
            { keys: "Ctrl + J", action: "Downloads", category: "History", description: "View downloads", useCase: "See downloaded files", tips: "Open download folder", os_specific: "Windows" },
            { keys: "F5", action: "Refresh", category: "Page", description: "Reload current page", useCase: "Update content", tips: "Ctrl+F5 hard refresh", os_specific: "Windows" },
            { keys: "Ctrl + R", action: "Refresh", category: "Page", description: "Reload page", useCase: "Refresh content", tips: "Alternative to F5", os_specific: "Windows" },
            { keys: "Ctrl + Shift + R", action: "Hard Refresh", category: "Page", description: "Refresh ignoring cache", useCase: "Clear cached content", tips: "Force reload", os_specific: "Windows" },
            { keys: "Esc", action: "Stop Loading", category: "Page", description: "Stop page load", useCase: "Cancel slow page", tips: "X button in address bar", os_specific: "Windows" },
            { keys: "Ctrl + F", action: "Find on Page", category: "Page", description: "Search within page", useCase: "Find specific text", tips: "Type to search", os_specific: "Windows" },
            { keys: "Ctrl + P", action: "Print", category: "Page", description: "Print current page", useCase: "Print webpage", tips: "Preview before printing", os_specific: "Windows" },
            { keys: "Ctrl + S", action: "Save Page", category: "Page", description: "Save webpage", useCase: "Offline access", tips: "HTML file", os_specific: "Windows" },
            { keys: "Ctrl + +", action: "Zoom In", category: "View", description: "Increase page zoom", useCase: "Larger text", tips: "Ctrl+0 to reset", os_specific: "Windows" },
            { keys: "Ctrl + -", action: "Zoom Out", category: "View", description: "Decrease page zoom", useCase: "Smaller text", tips: "Ctrl+0 to reset", os_specific: "Windows" },
            { keys: "Ctrl + 0", action: "Reset Zoom", category: "View", description: "Default zoom level", useCase: "Normal size", tips: "100% zoom", os_specific: "Windows" },
            { keys: "F11", action: "Full Screen", category: "View", description: "Toggle full screen mode", useCase: "Maximize viewing", tips: "Press again to exit", os_specific: "Windows" },
            { keys: "Alt + Left Arrow", action: "Back", category: "Navigation", description: "Go to previous page", useCase: "Navigate back", tips: "Mouse back button", os_specific: "Windows" },
            { keys: "Alt + Right Arrow", action: "Forward", category: "Navigation", description: "Go to next page", useCase: "Navigate forward", tips: "After going back", os_specific: "Windows" },
            { keys: "Ctrl + Enter", action: "Add .com", category: "Address Bar", description: "Add .com to typed address", useCase: "Quick URL entry", tips: "Type name, press Ctrl+Enter", os_specific: "Windows" },
            { keys: "F12", action: "Developer Tools", category: "Developer", description: "Open dev tools", useCase: "Debug websites", tips: "Inspect elements", os_specific: "Windows" },
            { keys: "Ctrl + Shift + I", action: "Developer Tools", category: "Developer", description: "Open dev tools", useCase: "Debug code", tips: "Console, elements, network", os_specific: "Windows" },
            { keys: "Ctrl + U", action: "View Source", category: "Developer", description: "View page source code", useCase: "See HTML", tips: "Raw code", os_specific: "Windows" },
            { keys: "Ctrl + Shift + Delete", action: "Clear Browsing Data", category: "General", description: "Open the clear browsing data dialog", useCase: "Clear cache, cookies, or history", tips: "Choose a time range before clearing", os_specific: "Windows" },
            { keys: "Ctrl + Shift + B", action: "Toggle Bookmarks Bar", category: "General", description: "Show or hide the bookmarks bar", useCase: "Reclaim vertical space or quickly re-show saved bookmarks", tips: "Bookmarks still work via the menu when hidden", os_specific: "Windows" },
            { keys: "Ctrl + Shift + O", action: "Open Bookmark Manager", category: "General", description: "Open the full bookmark manager in a new tab", useCase: "Organize and search all saved bookmarks", tips: "Different from Ctrl+D, which saves the current page", os_specific: "Windows" },
            { keys: "Shift + Esc", action: "Open Browser Task Manager", category: "Developer", description: "Open the browser's built-in task manager showing memory/CPU per tab and extension", useCase: "Find a tab or extension slowing the browser down", tips: "Different from the OS Task Manager (Ctrl+Shift+Esc)", os_specific: "Windows" }
        ]
    }
};

// Helper Functions
function getAppById(appId) {
    return SHORTCUTS_DB[appId] || null;
}

function getAllApps() {
    return Object.keys(SHORTCUTS_DB).map(key => ({
        id: key,
        name: SHORTCUTS_DB[key].name,
        platform: SHORTCUTS_DB[key].platform,
        icon: SHORTCUTS_DB[key].icon,
        shortcutCount: SHORTCUTS_DB[key].shortcuts.length,
        description: SHORTCUTS_DB[key].description
    }));
}

function getAppCategory(appId) {
    const categories = {
        windows_os: "Operating System",
        macos: "Operating System",
        linux_ubuntu: "Operating System",
        outlook: "Email & Calendar",
        excel: "Spreadsheets",
        word: "Word Processing",
        powerpoint: "Presentations",
        teams: "Communication",
        onenote: "Note Taking",
        project: "Project Management",
        photoshop: "Design",
        figma: "Design",
        vscode: "Development",
        browsers: "Web Browsers"
    };
    return categories[appId] || "Applications";
}

function searchShortcuts(query, platform = null) {
    const results = [];
    const searchTerm = query.toLowerCase();
    
    for (const [appId, app] of Object.entries(SHORTCUTS_DB)) {
        if (platform && app.platform !== platform && app.platform !== "windows") continue;
        
        const matches = app.shortcuts.filter(shortcut => 
            shortcut.keys.toLowerCase().includes(searchTerm) ||
            shortcut.action.toLowerCase().includes(searchTerm) ||
            (shortcut.description && shortcut.description.toLowerCase().includes(searchTerm)) ||
            (shortcut.category && shortcut.category.toLowerCase().includes(searchTerm))
        );
        
        if (matches.length > 0) {
            results.push({
                appId: appId,
                appName: app.name,
                appIcon: app.icon,
                shortcuts: matches
            });
        }
    }
    return results;
}